export const ADD_ENTRY = 'ADD_ENTRY';
export const DELETE_ENTRY ='DELETE_ENTRY';
export const FETCH_ENTRIES_SUCCESS='FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAIL='FETCH_ENTRIES_FAIL';
export const FETCH_ENTRIES_START='FETCH_ENTRIES_START';

// export const SET_ENTRIES='SET_ENTRIES';
// export const FETCH_ENTRIES_FAILED='FETCH_ENTRIES_FAILED';
